apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: buildah-task
spec:
  params:
    - name: image
      description: "The image to build and push"
      type: string
  workspaces:
    - name: source
      description: "Source code workspace"
  steps:
    - name: build
      env:
        - name: STORAGE_DRIVER
          value: vfs
      image: quay.io/buildah/stable:latest
      script: |
        #!/bin/bash
        set -e
        echo "Listing contents of the workspace directory:"
        ls "$workspaces_source_path"

        buildah bud --layers -t "localhost:5000/$(params.image):latest" $(workspaces.source.path)
        # buildah push "localhost:5000/$(params_image):latest"
    # - name: load-into-minikube
    #   image: quay.io/buildah/stable:latest
    #   script: |
    #     #!/bin/bash
    #     set -e
    #     buildah push localhost:5000/rust-app