apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: buildah-task
spec:
  params:
    - name: image
      description: "The image to build and push"
      type: string
  workspaces:
    - name: source
      description: "Source code workspace"
  steps:
    - name: build
      env:
        - name: STORAGE_DRIVER
          value: vfs
      image: quay.io/buildah/stable:latest
      script: |
        #!/bin/bash
        set -e
        # Build the image
        buildah bud --layers -t $(params.image) $(workspaces.source.path)
    - name: load-into-minikube
      image: quay.io/buildah/stable:latest
      script: |
        #!/bin/bash
        set -e
        buildah images -a
        buildah push rust-app:latest oci:/tmp/rust-app.tar
        eval $(minikube docker-env)
        docker load < /tmp/rust-app.tar