apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: build-docker
spec:
  params:
    - name: IMAGE
      type: string
    - name: CONTEXT
      type: string
  workspaces:
    - name: output
  steps:
    - name: build
      workingDir: $(workspaces.source.path)
      image: $(params.IMAGE)
      script:
        - /kaniko/executor
          --context "$(workspaces.output.path)"
          --dockerfile "$(workspaces.output.path)/Dockerfile"
    - name: load-to-minikube 
      image: bitnami/kubectl:1.19.7 
      script: | 
        #!/bin/sh 
        minikube image load $(params.IMAGE)