apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: build-and-deploy-pipeline
spec:
  tasks:
    - name: build-docker-image
      taskRef:
        name: build-docker
      params:
        - name: IMAGE
          value: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        - name: CONTEXT
          value: "/workspace/source"
