apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: clone-build-push
  namespace: default
spec:
  description: |
    This pipeline clones a git repo, builds a Docker image and
    pushes it to a registry
  params:
    - name: repo-url
      type: string
    - name: image
      type: string
  workspaces:
    - name: shared-data
  tasks:
    - name: fetch-source
      taskRef:
        name: git-clone
      workspaces:
        - name: output
          workspace: shared-data
      params:
        - name: url
          value: "https://github.com/AlicjaZub/rust-app.git"
    - name: build-and-push
      runAfter:
        - fetch-source
      taskRef:
        name: buildah-task
      params:
        - name: image
          value: $(params.image)
      workspaces:
        - name: source
          workspace: shared-data
